authors = ["Romain Monier <romain.monier@estudiants.urv.cat>",
           "Marlon Funk <marlonromanbenitofelix.funk@estudiants.urv.cat>"]
name = "BackPropagation"
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[compat]
julia = "1.8"
DataFrames = "1.4"
CSV = "0.10"